"""Decode the 8-char base32 cycle sync codes generated by the Lira mobile app.

Mirror of `src/cycleCode.ts`. Layout:
  bits 39..16 = 24-bit payload
    bits 23..10 = days since 2020-01-01 (UTC)
    bits 9..4   = cycleLength - 18  (range 18..81)
    bits 3..0   = periodLength - 1  (range 1..16)
  bits 15..0  = CRC16-CCITT over the 3 payload bytes (big-endian)

Visible form: `XXXX-XXXX` in Crockford base32 (alphabet 0-9 A-Z without
I, L, O, U). Decoder is forgiving — it strips dashes, normalises case and
silently corrects common look-alike typos before validating the checksum.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date, timedelta

ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
EPOCH = date(2020, 1, 1)


@dataclass(frozen=True)
class CycleCodePayload:
    start_date: date
    cycle_length: int
    period_length: int


def _crc16(data: bytes) -> int:
    crc = 0xFFFF
    for b in data:
        crc ^= (b & 0xFF) << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


def _normalise(raw: str) -> str:
    cleaned = "".join(ch for ch in raw.upper() if ch.isalnum())
    return (
        cleaned.replace("I", "1")
        .replace("L", "1")
        .replace("O", "0")
        .replace("U", "V")
    )


def decode_cycle_code(raw: str) -> CycleCodePayload | None:
    """Validate `raw` and return the embedded cycle data, or None on error."""
    if not raw:
        return None
    s = _normalise(raw)
    if len(s) != 8:
        return None
    value = 0
    for ch in s:
        try:
            idx = ALPHABET.index(ch)
        except ValueError:
            return None
        value = value * 32 + idx
    crc = value & 0xFFFF
    payload24 = (value >> 16) & 0xFFFFFF
    bytes_ = bytes(
        [
            (payload24 >> 16) & 0xFF,
            (payload24 >> 8) & 0xFF,
            payload24 & 0xFF,
        ]
    )
    if _crc16(bytes_) != crc:
        return None
    days = (payload24 >> 10) & 0x3FFF
    cycle_length = ((payload24 >> 4) & 0x3F) + 18
    period_length = (payload24 & 0x0F) + 1
    return CycleCodePayload(
        start_date=EPOCH + timedelta(days=days),
        cycle_length=cycle_length,
        period_length=period_length,
    )


def encode_cycle_code(payload: CycleCodePayload) -> str:
    """Encode a payload back into the canonical `XXXX-XXXX` form (used in tests)."""
    days = (payload.start_date - EPOCH).days
    if not 0 <= days < (1 << 14):
        raise ValueError("Date out of range")
    c = payload.cycle_length - 18
    if not 0 <= c < (1 << 6):
        raise ValueError("Cycle out of range")
    p = payload.period_length - 1
    if not 0 <= p < (1 << 4):
        raise ValueError("Period out of range")
    payload24 = (days << 10) | (c << 4) | p
    crc = _crc16(
        bytes(
            [
                (payload24 >> 16) & 0xFF,
                (payload24 >> 8) & 0xFF,
                payload24 & 0xFF,
            ]
        )
    )
    value = (payload24 << 16) | crc
    chars: list[str] = []
    for i in range(7, -1, -1):
        chars.append(ALPHABET[(value >> (i * 5)) & 0x1F])
    raw = "".join(chars)
    return f"{raw[:4]}-{raw[4:]}"
